# 注意: 教材 "线性代数及其应用" 的描述合并了两位贡献者的内容，因为目标格式不支持对同一本书进行多次评价。
course_name = "代数与几何"
course_code = "MATH1002"
notices = """"""

[[lecturers]]
name = "李文彬"
  [[lecturers.reviews]]
  content = """授课风格：幽默风趣。上课以板书为主，基本不用PPT。
上课无考勤，不点名
听课建议：若是已经提前学习了课程内容，可以不听课，自己学习其它。"""
  author = { name = "", link = "", date = "" }

[[lecturers]]
name = "梁慧"
  [[lecturers.reviews]]
  content = """授课风格：上课以板书为主，基本是复述一遍书上内容，有时稍有补充。除解析几何部分基本不用PPT。
上课有时考勤/点名
听课建议：若是已经提前学习了课程内容，可以不听课，自己学习其它。"""
  author = { name = "", link = "", date = "" }

[[lecturers]]
name = "史峰"
  [[lecturers.reviews]]
  content = """授课风格：偏学术性，拓展内容较为丰富，对入门不友好（但是平时自己研究些东西之后会发现他讲过）
上课无考勤
听课建议：建议自力更生"""
  author = { name = "", link = "", date = "" }

[[lecturers]]
name = "郑宝东"
  [[lecturers.reviews]]
  content = "Comments wanted here!"
  author = { name = "", link = "", date = "" }

[[lecturers]]
name = "曾吉文"
  [[lecturers.reviews]]
  content = """下面这位老师原为外聘教师，现已退休
授课风格：PPT + 板书。听课效果方面，不怎么好抓住重点，很多时候上完一节课，还是不知道关键的某些解题过程是怎么写的。
上课无考勤
听课建议：建议自力更生。"""
  author = { name = "", link = "", date = "" }

[[textbooks]]
title = "大学数学. 线性代数与空间解析几何"
book_author = "郑宝东，郭潇，王忠英编"
publisher = "高等教育出版社"
edition = "5版"
type = "textbook"
author = { name = "", link = "", date = "2021-11-01" }

[[textbooks]]
title = "线性代数及其应用"
book_author = "David C.Lay"
publisher = ""
edition = ""
type = "reference"
description = """有中译本，万能教材，但是部分翻译有点机械化，建议配合英文原版教材来看。
补充(by Oliver Wu): 讲解顺序非常自然，易于理解。例如，1-2 章，从线性方程组领起，再将其转化成向量方程和矩阵方程的形式，很好地将方程组解的性质、线性组合的性质和矩阵的性质结合在一起，后又通过可逆阵将它们联系起来；较早引入线性变换，让读者提前接受将矩阵视作变换的动态观点，并由此给出定义矩阵乘法的动机；第 3 章引入行列式的动机明确，由 Cramer 法则引出伴随阵和求逆方法比起工大的直接定义要清晰得多；等等。文字量虽大，但含大量例子，读起来并不费劲。"""
author = { name = "lmh12138", link = "https://github.com/lmh12138", date = "2022-07-23" }

[[textbooks]]
title = "Introduction to Linear Algebra"
book_author = "Gilbert Strang"
publisher = ""
edition = ""
type = "reference"
description = "清华近几年开始给本科生使用的教材，不过国内也是只有英文原版。"
author = { name = "lmh12138", link = "https://github.com/lmh12138", date = "2022-07-23" }

[[textbooks]]
title = "线性代数"
book_author = "Gilbert Strang"
publisher = "清华大学出版社"
edition = ""
type = "reference"
description = "黄色封皮的。"
author = { name = "lmh12138", link = "https://github.com/lmh12138", date = "2022-07-23" }

[[online_resources]]
title = "哈工大《线性代数》"
url = ""
description = "可以前往中国大学 MOOC上看哈工大的《线性代数》，或者去 B 站。"
author = { name = "", link = "", date = "" }

[[online_resources]]
title = "MIT 18.06 线性代数"
url = ""
description = """上知乎或者各个网站一搜都不可避免会提到在全球范围广受好评的 Strang 老爷子的线代神课，MIT的课程编号是 18.06，b站直接搜 「MIT 线性代数」有很多，虽说是 2011 年的视频了，但并不影响知识的学习，优秀的慕课和教材能使你的学习事半功倍。"""
author = { name = "lmh12138", link = "https://github.com/lmh12138", date = "2022-07-23" }

[[online_resources]]
title = "MIT 18.065 线性代数在数据分析、信号处理、机器学习中的应用"
url = ""
description = "算是个偏向 EECS 方向学生的线代课程，如果看完 18.06，还有余力的话可以继续看 18.065 试试。"
author = { name = "lmh12138", link = "https://github.com/lmh12138", date = "2022-07-23" }

course = []

[[exam]]
content = """考试整体难度适中（比高数简单一些），打分较友好。期中考平均分在 23 左右，期末考平均分在 40 左右，不捞人，挂科比例大约 1% 到 2%。

从 17 年至 20 年，考试风格略微有变，越来越注重对概念的理解，计算量不断增大，但证明题的思维难度在下降（特别是 20 届，期末考试已经删除证明题）。

23 年秋的代数与几何考试与 22 年的考试风格接近，考试回归计算，填空题和计算题主要考察各章所要求的各类计算，而选择题会出现概念辨析题，主要是课本上有的概念，思维量明显小于高数考试，主要突出一个计算能力，且不要求证明题。

24 年秋的在和本部联考后加入了多选题，难度略有上升，但是仍然没有要求证明题，主要考察还是各种概念的计算。"""
author = { name = "Gaster", link = "https://github.com/WDGaster703/", date = "2025-01-01" }

lab = []

[[advice]]
content = """作业的话一般交了就是最低分 18，写的认真、错误少就是 20（满分）。

学习时，要先将公式概念记熟，再将经典题型的思路理清，要不断锻炼自己的计算能力（思维量不大、基本在考计算）。

有时间想进一步提升，可以做参考书《线性代数与空间解析几何 疑难解答》《线性代数与空间解析几何 习题指导》上的题目。没时间的话，至少将作业题弄清楚。"""
author = { name = "", link = "", date = "" }

[[advice]]
content = """工大的教材过于枯燥和公式化，很多变换是拿来干嘛的都没有讲清楚，如果只是应付考试的话，如前述所说，看工大的 MOOC 并硬背教材公式即可。
但如果是想长远发展，比如以后想学习图形学、游戏开发等这些应用线代知识较多的工程应用场景，那么对数学知识原理的理解就是很有必要的。"""
author = { name = "lmh12138", link = "https://github.com/lmh12138", date = "2022-07-23" }

[[advice]]
content = "个人觉得大家不必太过惧怕英文教材，很多英文教材其实也就最开始需要查一查术语，原理讲述部分很多都比国内教材要好。"
author = { name = "lmh12138", link = "https://github.com/lmh12138", date = "2022-07-23" }

[[advice]]
content = "答疑可以直接问老师，老师一般会耐心解答。"
author = { name = "", link = "", date = "" }

schedule = []

[[related_links]]
content = "校内网盘教材资源: https://open.osa.moe/openauto/MATH1002/books"
author = { name = "lmh12138", link = "https://github.com/lmh12138", date = "2022-07-23" }

misc = []